"""Draws the fields for the two Japanese themes. Run from the repo root:

    python3 scripts/gen-japanese-patterns.py

Writes themes/wabi-sabi-seams.svg and themes/ukiyo-e-seigaiha.svg.

WABI-SABI — kintsugi. A glaze that has been broken and mended with lacquer and gold,
so the seams are the one bright thing on a dark, speckled stoneware ground. Cracks are
not drawn, they are GROWN: each is a random walk that drifts off its heading a little at
every step and now and then forks, which is how a fracture actually propagates through
a fired body. Where branches meet, gold pools into a small irregular patch, the way the
lacquer does in the real repairs. Every irregularity comes from a seeded RNG, so the
bowl breaks the same way every time the script runs.

The tile is seamless without any seam handling in the drawing: the whole crack network
is painted nine times, at every offset of one tile width and height, and the viewBox
clips it. A crack that leaves the right edge re-enters on the left because it was drawn
there too.

UKIYO-E — seigaiha, the "blue sea waves" of overlapping concentric arcs, which is the
sea in half the woodblock prints ever cut. Built the way it is printed: whole rows of
paper-colored discs, each carrying its rings, laid top to bottom so every row covers
the lower half of the row above. The discs are filled with the paper color rather than
masked, which makes the tile opaque: it IS the paper in that theme, and the graded sky
(bokashi) is laid over it in CSS rather than under it.
"""
import math, random

# ---- Wabi-sabi -----------------------------------------------------------------------
KW = 560                        # tile size, px — large, so the network does not read as a repeat
GOLD = '#D9AE55'                # the theme's --gold
RUST = '#9A6A45'                # iron spots in the clay
ASH = '#E8E2D4'                 # pale flecks in the glaze
rng = random.Random(1590)       # the year Rikyū's tea bowls were being made; any seed works


def grow(x, y, heading, length, width, depth, out, pools):
    """One crack: a jittered walk, forking with a small chance per step."""
    pts = [(x, y)]
    travelled = 0.0
    course = heading
    while travelled < length:
        step = rng.uniform(9, 20)
        # A fracture wanders but keeps its course: small drift, pulled back toward the
        # heading it started on, with the occasional hard kink where it met a flaw.
        # Without the pull the walk curls into loops, which reads as a river, not a break.
        heading += rng.gauss(0, 0.14) + (course - heading) * 0.12
        if rng.random() < 0.12:
            heading += rng.choice((-1, 1)) * rng.uniform(0.35, 0.7)
        x += math.cos(heading) * step
        y += math.sin(heading) * step
        travelled += step
        pts.append((x, y))
        if depth < 2 and rng.random() < 0.075:
            fork = heading + rng.choice((-1, 1)) * rng.uniform(0.5, 1.1)
            grow(x, y, fork, length * rng.uniform(0.25, 0.5), width * 0.7, depth + 1, out, pools)
            if rng.random() < 0.45:
                pools.append((x, y, width))
    out.append((pts, width))


def pool(x, y, w):
    """A small irregular gold patch where the lacquer gathered."""
    n = 9
    rad = rng.uniform(2.8, 5.5) + w
    pts = []
    for i in range(n):
        a = i / n * math.tau
        r = rad * rng.uniform(0.55, 1.25)
        pts.append((x + math.cos(a) * r, y + math.sin(a) * r * rng.uniform(0.6, 1.0)))
    return 'M' + 'L'.join(f'{px:.1f} {py:.1f}' for px, py in pts) + 'Z'


def wabi_sabi():
    cracks, pools = [], []
    # Four main fractures, each a long walk in a loose direction: a bowl breaks into a
    # few large pieces, not into gravel.
    for _ in range(4):
        grow(rng.uniform(0, KW), rng.uniform(0, KW), rng.uniform(0, math.tau),
             rng.uniform(380, 620), rng.uniform(1.3, 1.9), 0, cracks, pools)

    seams = []
    for pts, w in cracks:
        d = 'M' + 'L'.join(f'{x:.1f} {y:.1f}' for x, y in pts)
        seams.append(f'<path d="{d}" stroke-width="{w:.2f}"/>')
    patches = [f'<path d="{pool(x, y, w)}"/>' for x, y, w in pools]

    spots = []
    for _ in range(110):
        x, y = rng.uniform(0, KW), rng.uniform(0, KW)
        if rng.random() < 0.7:
            spots.append(f'<circle cx="{x:.1f}" cy="{y:.1f}" r="{rng.uniform(0.6, 1.7):.1f}" fill="{RUST}"/>')
        else:
            spots.append(f'<circle cx="{x:.1f}" cy="{y:.1f}" r="{rng.uniform(0.5, 1.1):.1f}" fill="{ASH}"/>')

    uses = ''.join(
        f'<use href="#net" x="{dx * KW}" y="{dy * KW}"/>'
        for dx in (-1, 0, 1) for dy in (-1, 0, 1)
    )
    return f'''<!-- Sidecar, Wabi-sabi background: kintsugi seams on speckled stoneware.
     Generated by scripts/gen-japanese-patterns.py; edit the script, not this file.
     The gold is kept low: at full strength the seams would compete with every line of
     text laid over them, and a mend is meant to be found, not announced. -->
<svg xmlns="http://www.w3.org/2000/svg" width="{KW}" height="{KW}" viewBox="0 0 {KW} {KW}">
<defs>
<g id="net">
<g opacity="0.16">{''.join(spots)}</g>
<g fill="none" stroke="{GOLD}" stroke-opacity="0.2" stroke-linecap="round" stroke-linejoin="round">{''.join(seams)}</g>
<g fill="{GOLD}" fill-opacity="0.2">{''.join(patches)}</g>
</g>
</defs>
{uses}
</svg>
'''


# ---- Ukiyo-e -------------------------------------------------------------------------
R = 20                          # one wave's radius, px
PAPER = '#F4ECDC'               # the theme's --bg: the tile is the paper
INDIGO = '#1F4E79'              # Prussian blue, the theme's --gold
RINGS = (1.0, 0.78, 0.56, 0.34)


def ukiyo_e():
    w, h = 4 * R, 2 * R         # two periods each way; the pattern repeats every 2R x R
    rows = []
    k = -2
    while k * R / 2 <= h + R:
        y = k * R / 2
        off = R if k % 2 else 0
        x = off - 2 * R
        while x <= w + 2 * R:
            rings = ''.join(
                f'<circle cx="{x:g}" cy="{y:g}" r="{R * f - 0.6:.2f}"/>' for f in RINGS[1:]
            )
            rows.append(
                f'<circle cx="{x:g}" cy="{y:g}" r="{R - 0.6:.2f}" fill="{PAPER}"/>{rings}'
            )
            x += 2 * R
        k += 1
    return f'''<!-- Sidecar, Ukiyo-e background: seigaiha, the blue sea waves.
     Generated by scripts/gen-japanese-patterns.py; edit the script, not this file.
     Opaque on purpose: the discs are filled with the paper color, so this tile is the
     paper and anything meant to sit on it (the graded sky) goes above it in CSS. -->
<svg xmlns="http://www.w3.org/2000/svg" width="{w}" height="{h}" viewBox="0 0 {w} {h}">
<rect width="{w}" height="{h}" fill="{PAPER}"/>
<g stroke="{INDIGO}" stroke-opacity="0.075" stroke-width="1.2" fill="none">{''.join(rows)}</g>
</svg>
'''


if __name__ == '__main__':
    with open('themes/wabi-sabi-seams.svg', 'w') as f:
        f.write(wabi_sabi())
    with open('themes/ukiyo-e-seigaiha.svg', 'w') as f:
        f.write(ukiyo_e())
    print('wrote themes/wabi-sabi-seams.svg and themes/ukiyo-e-seigaiha.svg')
