"""Draws the field for Film Noir. Run from the repo root:

    python3 scripts/gen-film-noir-film.py

Writes themes/film-noir-frames.svg, themes/film-noir-emulsion.svg and
themes/film-noir-damage.svg.

The panel is a close-up of a strip of 35mm film, the frame filling the panel's width
the way it fills the screen in a title sequence: four perforations down each side of
every frame, as the stock carries them, the frame window between, and the frame line
under each frame. Over that, the print has aged: its density is uneven, it has burns
and stains, rain (the short vertical flecks a worn print throws on the screen), long
scratches from the gate, dust, the odd hair, and grain. It is monochrome throughout,
because the theme is.

Every mark that AGES the print darkens it. On a black field, lightening is what spends
the contrast the hints sit on, so the burns, the mottling and the vignette are all
darker than the film, and the only light marks are the dust, the scratches and the
grain, each of them faint. test/theme-svg-assets.test.js measures the brightest pixel
they can make together against --muted.

The perforations are punched DARKER than the film rather than lit, for the same reason:
a hint that runs over one gains contrast instead of losing it. The structure comes from
the film base being the lightest of the three: the side strips and the frame line
between frames are a mid charcoal, and the frame windows and the holes are near black.
The first cut had all three within a few levels of each other, and the film vanished.

Three files because they repeat at three different sizes: the film at the panel's
width, so one frame always spans it; the emulsion on a square tile; the damage on a
tall one, so no scratch lines up with the frame it crosses. Everything irregular comes
from a seeded RNG, so the print ages the same way every time the script runs.
"""
import math, random

rng = random.Random(1941)       # The Maltese Falcon; any seed works

# ---- the film ---------------------------------------------------------------------------
FW, FH = 360, 196               # one frame, drawn at panel width; CSS scales it to fit
BASE = '#1C1C1C'                # the film base: side strips and the frame line
WINDOW = '#0B0B0B'              # the frame window, well under the base
HOLE = '#000000'                # the perforations: through the film to the dark behind


def frames():
    holes = []
    for x in (8, 326):
        for k in range(4):
            y = 49 * k + 15.5
            holes.append(f'<rect x="{x}" y="{y}" width="26" height="18" rx="3.5"/>')
    # The lip of each perforation catches a little light along its lower edge, which
    # is what makes a dark hole read as a hole rather than as a printed block.
    lips = ''.join(f'M{x + 3.5} {49 * k + 33.9}h19' for x in (8, 326) for k in range(4))
    return f'''<!-- Sidecar, Film Noir background: one frame of 35mm film at panel width.
     Generated by scripts/gen-film-noir-film.py; edit the script, not this file. -->
<svg xmlns="http://www.w3.org/2000/svg" width="{FW}" height="{FH}" viewBox="0 0 {FW} {FH}">
<rect width="{FW}" height="{FH}" fill="{BASE}"/>
<rect x="46" y="7" width="268" height="182" rx="10" fill="{WINDOW}"/>
<rect x="46.5" y="7.5" width="267" height="181" rx="9.5" fill="none" stroke="#FFFFFF" stroke-opacity="0.04"/>
<g fill="{HOLE}">{''.join(holes)}</g>
<path d="{lips}" stroke="#FFFFFF" stroke-opacity="0.04" stroke-width="0.8"/>
</svg>
'''


# ---- the emulsion: uneven density, burns, grain ------------------------------------------
EW = 480


def emulsion():
    burns = []
    for _ in range(6):
        x, y, r = rng.uniform(30, EW - 30), rng.uniform(30, EW - 30), rng.uniform(26, 72)
        burns.append(f'<circle cx="{x:.0f}" cy="{y:.0f}" r="{r:.0f}" fill-opacity="{rng.uniform(0.18, 0.28):.2f}" '
                     f'stroke="#000000" stroke-opacity="0.38" stroke-width="{rng.uniform(2, 4):.1f}"/>')
    return f'''<!-- Sidecar, Film Noir background: the aged emulsion. Darkens only, apart from the grain.
     Generated by scripts/gen-film-noir-film.py; edit the script, not this file. -->
<svg xmlns="http://www.w3.org/2000/svg" width="{EW}" height="{EW}" viewBox="0 0 {EW} {EW}">
<defs>
<filter id="density" x="0" y="0" width="100%" height="100%"><feTurbulence type="fractalNoise" baseFrequency="0.009" numOctaves="4" seed="11" stitchTiles="stitch"/>
<feColorMatrix values="0 0 0 0 0  0 0 0 0 0  0 0 0 0 0  -1.2 0 0 0 0.7"/></filter>
<filter id="burn" x="-25%" y="-25%" width="150%" height="150%"><feTurbulence type="fractalNoise" baseFrequency="0.035" numOctaves="2" seed="5" result="n"/>
<feDisplacementMap in="SourceGraphic" in2="n" scale="30" xChannelSelector="R" yChannelSelector="G" result="d"/><feGaussianBlur in="d" stdDeviation="2.2"/></filter>
<filter id="grain" x="0" y="0" width="100%" height="100%"><feTurbulence type="fractalNoise" baseFrequency="0.9" numOctaves="2" seed="3" stitchTiles="stitch"/>
<feColorMatrix values="0 0 0 0 1  0 0 0 0 1  0 0 0 0 1  0.55 0 0 0 -0.2"/></filter>
</defs>
<rect width="{EW}" height="{EW}" filter="url(#density)"/>
<g filter="url(#burn)" fill="#000000">{''.join(burns)}</g>
<g id="grain" opacity="0.05"><rect width="{EW}" height="{EW}" filter="url(#grain)"/></g>
</svg>
'''


# ---- the damage: rain, scratches, dust, hairs ---------------------------------------------
DW, DH = 420, 1100


def damage():
    parts = []
    for _ in range(60):             # rain: short vertical flecks
        x, y, L = rng.uniform(0, DW), rng.uniform(0, DH), rng.uniform(6, 26)
        parts.append(f'<path d="M{x:.1f} {y:.1f}v{L:.1f}" stroke="#FFFFFF" stroke-opacity="{rng.uniform(0.018, 0.032):.3f}" stroke-width="0.6"/>')
    for _ in range(6):              # scratches from the gate: long, wandering a little
        x, y0, L = rng.uniform(20, DW - 20), rng.uniform(-100, DH), rng.uniform(200, 800)
        pts, y, dx = [], y0, 0.0
        while y < y0 + L:
            dx += rng.gauss(0, 0.05)
            pts.append((x + dx * 6, y))
            y += 12
        d = 'M' + 'L'.join(f'{px:.1f} {py:.1f}' for px, py in pts)
        parts.append(f'<path d="{d}" stroke="#FFFFFF" stroke-opacity="{rng.uniform(0.025, 0.038):.3f}" '
                     f'stroke-width="{rng.choice((0.6, 0.9))}" fill="none"/>')
    for _ in range(110):            # dust
        x, y = rng.uniform(0, DW), rng.uniform(0, DH)
        r = rng.choice((0.5, 0.6, 0.8, 1.0, 1.4, 2.0))
        parts.append(f'<circle cx="{x:.1f}" cy="{y:.1f}" r="{r}" fill="#FFFFFF" fill-opacity="{rng.uniform(0.025, 0.04):.3f}"/>')
    for _ in range(8):              # hairs caught in the gate
        x, y = rng.uniform(0, DW), rng.uniform(0, DH)
        a, L = rng.uniform(0, math.tau), rng.uniform(10, 26)
        c = (x + math.cos(a) * L * 0.5 + rng.uniform(-9, 9), y + math.sin(a) * L * 0.5 + rng.uniform(-9, 9))
        e = (x + math.cos(a) * L, y + math.sin(a) * L)
        parts.append(f'<path d="M{x:.1f} {y:.1f}Q{c[0]:.1f} {c[1]:.1f} {e[0]:.1f} {e[1]:.1f}" '
                     f'stroke="#FFFFFF" stroke-opacity="0.036" stroke-width="0.6" fill="none"/>')
    return f'''<!-- Sidecar, Film Noir background: the damage a worn print carries.
     Generated by scripts/gen-film-noir-film.py; edit the script, not this file.
     Every mark is faint white, and the strongest is a measured ceiling: see
     test/theme-svg-assets.test.js. -->
<svg xmlns="http://www.w3.org/2000/svg" width="{DW}" height="{DH}" viewBox="0 0 {DW} {DH}">{''.join(parts)}</svg>
'''


if __name__ == '__main__':
    for name, draw in (('frames', frames), ('emulsion', emulsion), ('damage', damage)):
        with open(f'themes/film-noir-{name}.svg', 'w') as f:
            f.write(draw())
    print('wrote themes/film-noir-frames.svg, film-noir-emulsion.svg and film-noir-damage.svg')
