#!/usr/bin/env bash
# Packages a Sidecar release zip from a git tag into dist/.
#
# The GitHub Release is the canonical home for release zips; this script just
# builds the local artifact to upload. dist/ is gitignored — nothing here is
# committed. The output is a flat-root zip (manifest.json at the top, no wrapper
# folder) ready for the Chrome Web Store and a GitHub Release asset.
#
# Usage: scripts/package.sh [vX.Y.Z]   (default: the manifest's current version)
#
# What it does: git archive the tag → strip docs/dev/tooling (README, CHANGELOG,
# PRIVACY.md, scripts/, assets/, .github/, …) → regenerate version.js (gitignored,
# stamped to the tag's short commit, clean) → zip → print sha256 + file count.
set -euo pipefail
cd "$(dirname "$0")/.."

MANIFEST_VERSION=$(grep -m1 '"version"' manifest.json | sed -E 's/.*"version"[^"]*"([^"]+)".*/\1/')
TAG="${1:-v${MANIFEST_VERSION}}"

if ! git rev-parse --verify --quiet "refs/tags/${TAG}" >/dev/null; then
  echo "Tag '${TAG}' not found. Usage: scripts/package.sh [vX.Y.Z]" >&2
  exit 1
fi
if ! git diff --quiet || ! git diff --cached --quiet; then
  echo "Working tree is dirty — commit or stash before packaging so the zip matches the tag." >&2
  exit 1
fi

SHORT=$(git rev-parse --short "${TAG}^{commit}")
VERSION_NO_V="${TAG#v}"
OUT="dist/sidecar-${VERSION_NO_V}.zip"

STAGE="$(mktemp -d)/sidecar"
mkdir -p "${STAGE}"
git archive "${TAG}" | tar -x -C "${STAGE}"

# Strip everything that isn't part of the running extension.
rm -rf "${STAGE}/.claude" "${STAGE}/.github" "${STAGE}/scripts" "${STAGE}/assets"
rm -f "${STAGE}/.gitignore" "${STAGE}/README.md" "${STAGE}/CHANGELOG.md" \
      "${STAGE}/FEATURES.md" "${STAGE}/PRIVACY.md" "${STAGE}/BROWSER_PARITY.md" \
      "${STAGE}/VENDOR.md" "${STAGE}/package.json"

# version.js is gitignored and not in the archive — regenerate it, stamped to the tag.
cat > "${STAGE}/version.js" <<EOF
// Auto-generated by scripts/stamp-version.sh — do not edit. (gitignored)
window.SIDECAR_BUILD = { version: '${VERSION_NO_V}', commit: '${SHORT}' };
EOF

mkdir -p dist
rm -f "${OUT}"
( cd "${STAGE}" && zip -rqX "${OLDPWD}/${OUT}" . -x ".*" )

FILES=$(unzip -Z1 "${OUT}" | grep -vc '/$')
SHA=$(shasum -a 256 "${OUT}" | awk '{print $1}')
echo "Built ${OUT}"
echo "  tag:      ${TAG} (${SHORT})"
echo "  files:    ${FILES}"
echo "  sha256:   ${SHA}"
