#!/usr/bin/env bash
# Packages Sidecar release zips (Chrome + Firefox) from a git tag into dist/.
#
# The GitHub Release is the canonical home for release zips; this script just
# builds the local artifacts to upload. dist/ is gitignored — nothing here is
# committed. Each output is a flat-root zip (manifest.json at the top, no wrapper
# folder): sidecar-X.Y.Z.zip for the Chrome Web Store, sidecar-X.Y.Z-firefox.zip
# for AMO.
#
# Sidecar ships ONE unified codebase; the only per-store difference is the
# manifest. The repo keeps the union of both browsers' keys (so dev-loading
# unpacked works in either browser with no build step); at package time this
# strips each store's zip down to the keys that store actually uses:
#   Chrome  — drops sidebar_action, browser_specific_settings, background.scripts
#   Firefox — drops side_panel, minimum_chrome_version, background.service_worker
# so neither store's validator sees the other's keys (avoids a Chrome Web Store
# rejection on the Firefox-only keys, and console warnings on both sides).
# Requires node (dev-time only; not shipped) for the manifest edit.
#
# Usage: scripts/package.sh [vX.Y.Z]   (default: the manifest's current version)
set -euo pipefail
cd "$(dirname "$0")/.."
ROOT="$PWD"

MANIFEST_VERSION=$(grep -m1 '"version"' manifest.json | sed -E 's/.*"version"[^"]*"([^"]+)".*/\1/')
TAG="${1:-v${MANIFEST_VERSION}}"

if ! git rev-parse --verify --quiet "refs/tags/${TAG}" >/dev/null; then
  echo "Tag '${TAG}' not found. Usage: scripts/package.sh [vX.Y.Z]" >&2
  exit 1
fi
if ! git diff --quiet || ! git diff --cached --quiet; then
  echo "Working tree is dirty — commit or stash before packaging so the zip matches the tag." >&2
  exit 1
fi

SHORT=$(git rev-parse --short "${TAG}^{commit}")
VERSION_NO_V="${TAG#v}"
# The tag's own commit date, used to stamp every file in the zip. Derived from the
# tag rather than "now" so the build is a function of the tag alone, and forced to
# UTC so it does not depend on the packager's timezone. `touch -t` format, which
# both BSD and GNU touch accept — BSD's -d rejects git's ISO offset.
SOURCE_DATE=$(TZ=UTC git log -1 --format=%cd --date=format-local:'%Y%m%d%H%M.%S' "${TAG}^{commit}")

STAGE="$(mktemp -d)/sidecar"
mkdir -p "${STAGE}"
git archive "${TAG}" | tar -x -C "${STAGE}"

# Strip everything that isn't part of the running extension.
rm -rf "${STAGE}/.claude" "${STAGE}/.github" "${STAGE}/scripts" "${STAGE}/assets" "${STAGE}/test" \
       "${STAGE}/docs"
# Every top-level .md, by glob rather than by name. The old explicit list failed
# open: a doc added later shipped inside the extension until someone noticed, and
# REVIEWERS.md — written FOR the store, describing how to reproduce this very zip
# — was about to be the next one. Nothing in the package references a bundled .md
# (help.html's changelog and privacy links point at GitHub), so the glob is safe.
# NOTICE has no extension and stays: it's the vendored licenses.
rm -f "${STAGE}"/*.md "${STAGE}/.gitignore" "${STAGE}/package.json"

# version.js is gitignored and not in the archive — regenerate it, stamped to the tag.
cat > "${STAGE}/version.js" <<EOF
// Auto-generated by scripts/stamp-version.sh — do not edit. (gitignored)
window.SIDECAR_BUILD = { version: '${VERSION_NO_V}', commit: '${SHORT}' };
EOF

# The archived manifest carries both browsers' keys; each zip gets only its own.
PRISTINE_MANIFEST="$(mktemp)"
cp "${STAGE}/manifest.json" "${PRISTINE_MANIFEST}"

build_zip() {
  local target="$1" out="$2"
  cp "${PRISTINE_MANIFEST}" "${STAGE}/manifest.json"
  node -e '
    const fs = require("fs");
    const file = process.argv[1], target = process.argv[2];
    const m = JSON.parse(fs.readFileSync(file, "utf8"));
    if (target === "chrome") {
      delete m.sidebar_action;
      delete m.browser_specific_settings;
      if (m.background) delete m.background.scripts;
    } else {
      delete m.side_panel;
      delete m.minimum_chrome_version;
      // externally_connectable is Chrome-schema only (Firefox never supported
      // it and defaults to deny anyway); drop it so the AMO validator does not
      // flag an unrecognized manifest key in the Firefox zip.
      delete m.externally_connectable;
      // sidePanel is a Chrome-only permission; drop it so the AMO
      // validator does not flag an unrecognized permission in the Firefox zip.
      if (Array.isArray(m.permissions)) {
        m.permissions = m.permissions.filter((p) => p !== "sidePanel");
      }
      if (m.background) delete m.background.service_worker;
    }
    fs.writeFileSync(file, JSON.stringify(m, null, 2) + "\n");
  ' "${STAGE}/manifest.json" "${target}"
  rm -f "${ROOT}/${out}"
  # Deterministic output. Every file is stamped with the tag's commit date and
  # entries are added in sorted order, so the same tag always produces the same
  # bytes on any machine. That turns the published SHA-256 into something a
  # reviewer can reproduce and check, instead of "extract both and trust the
  # diff" — which matters now that AMO requires a source submission alongside
  # every upload (see REVIEWERS.md).
  find "${STAGE}" -exec touch -t "${SOURCE_DATE}" {} +
  ( cd "${STAGE}" && find . -type f ! -name '.*' | LC_ALL=C sort | zip -qXD "${ROOT}/${out}" -@ )
  local files sha
  files=$(unzip -Z1 "${ROOT}/${out}" | grep -vc '/$')
  sha=$(shasum -a 256 "${ROOT}/${out}" | awk '{print $1}')
  echo "Built ${out}  [${target}]"
  echo "  files:   ${files}"
  echo "  sha256:  ${sha}"
}

mkdir -p dist
echo "Packaging ${TAG} (${SHORT})"
# Both outputs carry their store's name — the Chrome zip used to be bare
# sidecar-X.Y.Z.zip, which read as "the" package and had people reaching for the
# wrong file. 1.10.0 and earlier keep the old name (published, never renamed).
build_zip chrome  "dist/sidecar-${VERSION_NO_V}-chrome.zip"
build_zip firefox "dist/sidecar-${VERSION_NO_V}-firefox.zip"
