#!/usr/bin/env bash
# Generates version.js from the manifest version + current git commit, so the
# About dialog can show exactly which build is loaded. version.js is gitignored
# and regenerated locally (see .git/hooks/post-commit). There is no build step,
# so the unpacked extension reads this file directly at runtime.
set -euo pipefail
cd "$(dirname "$0")/.."

VERSION=$(grep -m1 '"version"' manifest.json | sed -E 's/.*"version"[^"]*"([^"]+)".*/\1/')
COMMIT=$(git rev-parse --short HEAD 2>/dev/null || echo dev)
# Mark a dirty working tree so a hand-modified load is distinguishable.
if ! git diff --quiet 2>/dev/null || ! git diff --cached --quiet 2>/dev/null; then
  COMMIT="${COMMIT}+"
fi

cat > version.js <<EOF
// Auto-generated by scripts/stamp-version.sh — do not edit. (gitignored)
window.SIDECAR_BUILD = { version: '${VERSION}', commit: '${COMMIT}' };
EOF

echo "Stamped version.js: ${VERSION} (${COMMIT})"
